#DATABASE.YML FILE TEMPLATE

development:
  adapter: postgresql
  database: playground_development
  user: postgres
  password: password
  host: localhost

test:
  adapter: postgresql
  database: playground_test
  user: postgres
  password: password
  host: localhost

#CREATE THE DATABASE AFTERWARDS
